// Vocabulary Database for Word of the Day
// Levels: beginner, intermediate, advanced

const WORD_OF_THE_DAY_DB = [
    // --- Beginner (A1-A2) ---
    { word: 'Creative', level: 'beginner', phonetic: '/kriˈeɪ.t̬ɪv/', translation: '有創造力的', examples: ['Children are very creative.', 'She has some creative ideas for the project.'] },
    { word: 'Reliable', level: 'beginner', phonetic: '/rɪˈlaɪ.ə.bəl/', translation: '可靠的', examples: ['My car is old but reliable.', 'He is a reliable friend.'] },
    { word: 'Opportunity', level: 'beginner', phonetic: '/ˌɑː.pɚˈtuː.nə.t̬i/', translation: '機會', examples: ['This is a great opportunity to learn.', 'Don\'t miss this opportunity.'] },
    { word: 'Essential', level: 'beginner', phonetic: '/ɪˈsen.ʃəl/', translation: '必要的；不可或缺的', examples: ['Water is essential for life.', 'It is essential to arrive on time.'] },
    { word: 'Healthy', level: 'beginner', phonetic: '/ˈhel.θi/', translation: '健康的', examples: ['She looks very healthy.', 'A healthy diet is important.'] },
    { word: 'Simple', level: 'beginner', phonetic: '/ˈsɪm.pəl/', translation: '簡單的', examples: ['The logic is very simple.', 'It was a simple mistake.'] },
    { word: 'Adventure', level: 'beginner', phonetic: '/ədˈven.tʃɚ/', translation: '冒險', examples: ['Traveling to a new country is an adventure.', 'They are looking for adventure.'] },
    { word: 'Balance', level: 'beginner', phonetic: '/ˈbæl.əns/', translation: '平衡', examples: ['Maintaining a work-life balance is important.', 'He lost his balance and fell.'] },
    { word: 'Curious', level: 'beginner', phonetic: '/ˈkjʊr.i.əs/', translation: '好奇的', examples: ['Cats are naturally curious.', 'I am curious about the result.'] },
    { word: 'Famous', level: 'beginner', phonetic: '/ˈfeɪ.məs/', translation: '著名的', examples: ['She is a famous singer.', 'Paris is famous for its museums.'] },
    { word: 'Honest', level: 'beginner', phonetic: '/ˈɑː.nɪst/', translation: '誠實的', examples: ['To be honest, I don\'t like it.', 'He gave an honest answer.'] },
    { word: 'Imagine', level: 'beginner', phonetic: '/ɪˈmædʒ.ɪn/', translation: '想像', examples: ['Can you imagine living on Mars?', 'Imagine what we could do together.'] },
    { word: 'Journey', level: 'beginner', phonetic: '/ˈdʒɝː.ni/', translation: '旅程', examples: ['It was a long and tiring journey.', 'Life is a beautiful journey.'] },
    { word: 'Opinion', level: 'beginner', phonetic: '/əˈpɪn.jən/', translation: '意見', examples: ['In my opinion, this is better.', 'Everyone is entitled to their own opinion.'] },
    { word: 'Patient', level: 'beginner', phonetic: '/ˈpɪ.ʃənt/', translation: '有耐心的', examples: ['You need to be patient with children.', 'Please be patient; we are working on it.'] },
    { word: 'Beautiful', level: 'beginner', phonetic: '/ˈbjuː.t̬ə.fəl/', translation: '漂亮的', examples: ['What a beautiful sunset!', 'She has a beautiful voice.'] },
    { word: 'Careful', level: 'beginner', phonetic: '/ˈker.fəl/', translation: '小心的', examples: ['Be careful with that glass.', 'You should be more careful next time.'] },
    { word: 'Difficult', level: 'beginner', phonetic: '/ˈdɪf.ə.kəlt/', translation: '困難的', examples: ['The exam was very difficult.', 'It is difficult to say who is right.'] },
    { word: 'Excellent', level: 'beginner', phonetic: '/ˈek.səl.ənt/', translation: '優秀的', examples: ['She did an excellent job.', 'This is an excellent restaurant.'] },
    { word: 'Friendship', level: 'beginner', phonetic: '/ˈfrend.ʃɪp/', translation: '友誼', examples: ['Our friendship is very important to me.', 'They have a strong friendship.'] },
    { word: 'General', level: 'beginner', phonetic: '/ˈdʒen.ər.əl/', translation: '一般的', examples: ['In general, I agree with you.', 'This is a general rule.'] },
    { word: 'History', level: 'beginner', phonetic: '/ˈhɪs.t̬ɚ.i/', translation: '歷史', examples: ['I like learning about history.', 'This city has a long history.'] },
    { word: 'Interest', level: 'beginner', phonetic: '/ˈɪn.trɪst/', translation: '興趣', examples: ['I have an interest in music.', 'Do you have any special interests?'] },
    { word: 'Kitchen', level: 'beginner', phonetic: '/ˈkɪtʃ.ən/', translation: '廚房', examples: ['She is in the kitchen.', 'We need to clean the kitchen.'] },
    { word: 'Language', level: 'beginner', phonetic: '/ˈlæŋ.ɡwɪdʒ/', translation: '語言', examples: ['How many languages do you speak?', 'English is a universal language.'] },
    { word: 'Mountain', level: 'beginner', phonetic: '/ˈmaʊn.tən/', translation: '山', examples: ['They climbed the mountain.', 'The view from the mountain was great.'] },
    { word: 'Neighborhood', level: 'beginner', phonetic: '/ˈneɪ.bɚ.hʊd/', translation: '鄰里', examples: ['It is a quiet neighborhood.', 'I like my neighborhood.'] },
    { word: 'Personal', level: 'beginner', phonetic: '/ˈpɝː.sən.əl/', translation: '個人的', examples: ['This is my personal opinion.', 'I have some personal matters to attend to.'] },
    { word: 'Question', level: 'beginner', phonetic: '/ˈkwes.tʃən/', translation: '問題', examples: ['I have a question for you.', 'Can you answer this question?'] },
    { word: 'Recently', level: 'beginner', phonetic: '/ˈriː.sənt.li/', translation: '最近', examples: ['I saw him recently.', 'Have you been there recently?'] },
    { word: 'Special', level: 'beginner', phonetic: '/ˈspeʃ.əl/', translation: '特別的', examples: ['Today is a special day.', 'Do you have any special plans?'] },
    { word: 'Together', level: 'beginner', phonetic: '/təˈɡeð.ɚ/', translation: '一起', examples: ['We can work together.', 'Let\'s go together.'] },
    { word: 'Understand', level: 'beginner', phonetic: '/ˌʌn.dɚˈstænd/', translation: '理解', examples: ['I don\'t understand this.', 'Do you understand what I mean?'] },
    { word: 'Vacation', level: 'beginner', phonetic: '/veɪˈkeɪ.ʃən/', translation: '假期', examples: ['Where are you going for vacation?', 'I need a long vacation.'] },
    { word: 'Weather', level: 'beginner', phonetic: '/ˈweð.ɚ/', translation: '天氣', examples: ['What is the weather like today?', 'The weather is very nice.'] },
    { word: 'Yesterday', level: 'beginner', phonetic: '/ˈjes.tɚ.deɪ/', translation: '昨天', examples: ['I saw her yesterday.', 'What did you do yesterday?'] },
    { word: 'Between', level: 'beginner', phonetic: '/bɪˈtwiːn/', translation: '在...之間', examples: ['The store is between the bank and the park.', 'Choose between the two options.'] },
    { word: 'Comfortable', level: 'beginner', phonetic: '/ˈkʌm.fɚ.t̬ə.bəl/', translation: '舒適的', examples: ['This chair is very comfortable.', 'I feel comfortable here.'] },
    { word: 'Dangerous', level: 'beginner', phonetic: '/ˈdeɪn.dʒɚ.əs/', translation: '危險的', examples: ['It is dangerous to walk alone at night.', 'The situation is dangerous.'] },
    { word: 'Everything', level: 'beginner', phonetic: '/ˈev.ri.θɪŋ/', translation: '一切', examples: ['Everything is going well.', 'I have everything I need.'] },

    // --- Intermediate (B1-B2) ---
    { word: 'Fascinating', level: 'intermediate', phonetic: '/ˈfæs.ən.eɪ.tɪŋ/', translation: '迷人的；極有吸引力的', examples: ['The book I read last night was truly fascinating.', 'The documentary offers a fascinating insight.'] },
    { word: 'Accomplish', level: 'intermediate', phonetic: '/əˈkɑːm.plɪʃ/', translation: '完成；實現', examples: ['We can accomplish great things together.', 'It took her three years to accomplish her goal.'] },
    { word: 'Versatile', level: 'intermediate', phonetic: '/ˈvɝː.sə.t̬əl/', translation: '多才多藝的；多用途的', examples: ['He is a versatile actor.', 'This kitchen tool is incredibly versatile.'] },
    { word: 'Challenge', level: 'intermediate', phonetic: '/ˈtʃæl.ɪndʒ/', translation: '挑戰', examples: ['Learning a new language is a challenge.', 'We faced many challenges during the project.'] },
    { word: 'Distraction', level: 'intermediate', phonetic: '/dɪˈstræk.ʃən/', translation: '分心；分心事物', examples: ['I need quiet to work without distractions.', 'Phone notifications are a major distraction.'] },
    { word: 'Enthusiastic', level: 'intermediate', phonetic: '/ɪnˌθuː.ziˈæs.tɪk/', translation: '熱情的', examples: ['The team was very enthusiastic about the plan.', 'She is an enthusiastic supporter of the arts.'] },
    { word: 'Alternative', level: 'intermediate', phonetic: '/ɑːlˈtɝː.nə.t̬ɪv/', translation: '替代方案', examples: ['We need to find an alternative solution.', 'Is there any alternative to surgery?'] },
    { word: 'Beneficial', level: 'intermediate', phonetic: '/ˌben.əˈfɪʃ.əl/', translation: '有益的', examples: ['Regular exercise is beneficial to health.', 'This experience was very beneficial for me.'] },
    { word: 'Consequence', level: 'intermediate', phonetic: '/ˈkɑːn.sə.kwəns/', translation: '後果', examples: ['Actions have consequences.', 'We must consider the consequence of our choice.'] },
    { word: 'Efficient', level: 'intermediate', phonetic: '/ɪˈfɪʃ.ənt/', translation: '有效率的', examples: ['The new system is much more efficient.', 'She is an efficient worker.'] },
    { word: 'Fundamental', level: 'intermediate', phonetic: '/ˌfʌn.dəˈmen.t̬əl/', translation: '基礎的；根本的', examples: ['Education is a fundamental right.', 'There are fundamental differences between them.'] },
    { word: 'Guarantee', level: 'intermediate', phonetic: '/ˌɡer.ənˈtiː/', translation: '保證', examples: ['We cannot guarantee success.', 'The product comes with a two-year guarantee.'] },
    { word: 'Negotiate', level: 'intermediate', phonetic: '/nəˈɡoʊ.ʃi.eɪt/', translation: '協商；談判', examples: ['They are trying to negotiate a new contract.', 'He skills are useful when you negotiate.'] },
    { word: 'Objective', level: 'intermediate', phonetic: '/əbˈdʒektɪv/', translation: '目標', examples: ['Our primary objective is to improve quality.', 'Try to be objective when judging the work.'] },
    { word: 'Significant', level: 'intermediate', phonetic: '/sɪɡˈnɪf.ə.kənt/', translation: '重大的；顯著的', examples: ['There has been a significant improvement.', 'This is a significant discovery for science.'] },
    { word: 'Analyze', level: 'intermediate', phonetic: '/ˈæn.əl.aɪz/', translation: '分析', examples: ['We need to analyze the data.', 'They analyzed the situation carefully.'] },
    { word: 'Collaborate', level: 'intermediate', phonetic: '/kəˈlæb.ə.reɪt/', translation: '協作', examples: ['We need to collaborate on this project.', 'They collaborated with several foreign companies.'] },
    { word: 'Description', level: 'intermediate', phonetic: '/dɪˈskrɪp.ʃən/', translation: '描述', examples: ['Can you give me a description of the man?', 'This is a brief description of the project.'] },
    { word: 'Enormous', level: 'intermediate', phonetic: '/ɪˈnɔːr.məs/', translation: '巨大的', examples: ['The house is enormous.', 'An enormous amount of work was involved.'] },
    { word: 'Flexible', level: 'intermediate', phonetic: '/ˈflek.sə.bəl/', translation: '靈活的', examples: ['We need a flexible approach.', 'My working hours are flexible.'] },
    { word: 'Hypothesis', level: 'intermediate', phonetic: '/haɪˈpɑː.θə.sɪs/', translation: '假設', examples: ['The experimental results supported the hypothesis.', 'Let\'s start with a simple hypothesis.'] },
    { word: 'Incentive', level: 'intermediate', phonetic: '/ɪnˈsen.t̬ɪv/', translation: '激勵', examples: ['The bonus is a great incentive.', 'There is no incentive for people to work hard.'] },
    { word: 'Journalist', level: 'intermediate', phonetic: '/ˈdʒɝː.nə.lɪst/', translation: '記者', examples: ['She is a professional journalist.', 'The journalist interviewed several witnesses.'] },
    { word: 'Knowledgeable', level: 'intermediate', phonetic: '/ˈnɑː.lɪ.dʒə.bəl/', translation: '知識淵博的', examples: ['He is very knowledgeable about world history.', 'She is knowledgeable in her field.'] },
    { word: 'Limitation', level: 'intermediate', phonetic: '/ˌlɪm.əˈteɪ.ʃən/', translation: '限制', examples: ['There are limitations to what we can do.', 'We must recognize our own limitations.'] },
    { word: 'Motivation', level: 'intermediate', phonetic: '/ˌmoʊ.t̬əˈveɪ.ʃən/', translation: '動力', examples: ['What is your motivation for learning English?', 'He lacks motivation.'] },
    { word: 'Numerous', level: 'intermediate', phonetic: '/ˈnuː.mə.rəs/', translation: '許多的', examples: ['There are numerous reasons for this.', 'Numerous studies have shown the benefits.'] },
    { word: 'Observe', level: 'intermediate', phonetic: '/əbˈzɝːv/', translation: '觀察', examples: ['Scientists observe the behavior of animals.', 'She observed the children playing.'] },
    { word: 'Perspective', level: 'intermediate', phonetic: '/pɚˈspek.tɪv/', translation: '視角；看法', examples: ['Try to look at it from another perspective.', 'The book provides a fresh perspective.'] },
    { word: 'Qualified', level: 'intermediate', phonetic: '/ˈkwɑː.lə.faɪd/', translation: '合格的', examples: ['He is highly qualified for the job.', 'Are you qualified to teach English?'] },
    { word: 'Regardless', level: 'intermediate', phonetic: '/rɪˈɡɑːrd.ləs/', translation: '不管怎樣', examples: ['I will go regardless of the weather.', 'Regardless of the cost, we must finish it.'] },
    { word: 'Sophisticated', level: 'intermediate', phonetic: '/səˈfɪs.tə.keɪ.t̬ɪd/', translation: '複雜的；高級的', examples: ['The system is very sophisticated.', 'She is a sophisticated woman.'] },
    { word: 'Temporary', level: 'intermediate', phonetic: '/ˈtem.pə.rer.i/', translation: '臨時的', examples: ['This is only a temporary solution.', 'He has a temporary job.'] },
    { word: 'Utilize', level: 'intermediate', phonetic: '/ˈjuː.t̬əl.aɪz/', translation: '利用', examples: ['We must utilize our resources effectively.', 'The new technology is utilized in several fields.'] },
    { word: 'Vulnerable', level: 'intermediate', phonetic: '/ˈvʌl.nɚ.ə.bəl/', translation: '脆弱的', examples: ['The elderly are more vulnerable to diseases.', 'The situation is very vulnerable.'] },
    { word: 'Widespread', level: 'intermediate', phonetic: '/ˈwaɪd.spred/', translation: '廣泛的', examples: ['The problem is widespread.', 'The news received widespread coverage.'] },
    { word: 'Yield', level: 'intermediate', phonetic: '/jiːld/', translation: '產生；屈服', examples: ['The investment will yield high returns.', 'They refused to yield to the pressure.'] },
    { word: 'Zodiac', level: 'intermediate', phonetic: '/ˈzoʊ.di.æk/', translation: '黃道帶；星座', examples: ['Which zodiac sign are you?', 'The Chinese zodiac is very interesting.'] },
    { word: 'Acquisition', level: 'intermediate', phonetic: '/ˌæk.wəˈzɪʃ.ən/', translation: '收購；獲得', examples: ['The company made a new acquisition.', 'The acquisition of knowledge is a lifelong process.'] },
    { word: 'Broadcast', level: 'intermediate', phonetic: '/ˈbrɑːd.kæst/', translation: '廣播', examples: ['The program will be broadcast tonight.', 'The news was broadcast around the world.'] },

    // --- Advanced (C1-C2) ---
    { word: 'Resilient', level: 'advanced', phonetic: '/rɪˈzɪl.jənt/', translation: '有韌性的；適應力強的', examples: ['Children are often very resilient.', 'The economy is surprisingly resilient.'] },
    { word: 'Empathy', level: 'advanced', phonetic: '/ˈem.pə.θi/', translation: '同理心；共鳴', examples: ['Having empathy is important for relationships.', 'He showed great empathy toward the victims.'] },
    { word: 'Initiative', level: 'advanced', phonetic: '/ɪˈnɪʃ.ə.t̬ɪv/', translation: '主動性；倡議', examples: ['She took the initiative to organize the event.', 'The government launched a new initiative.'] },
    { word: 'Innovative', level: 'advanced', phonetic: '/ˈɪn.ə.veɪ.t̬ɪv/', translation: '創新的', examples: ['The company is known for its innovative approach.', 'We need innovative solutions to this problem.'] },
    { word: 'Plausible', level: 'advanced', phonetic: '/ˈplɑː.zə.bəl/', translation: '貌似合理的；說得通的', examples: ['The explanation sounds plausible.', 'Is there a plausible reason for the delay?'] },
    { word: 'Ubiquitous', level: 'advanced', phonetic: '/juːˈbɪk.wə.t̬əs/', translation: '無所不在的', examples: ['Mobile phones are now ubiquitous.', 'His influence is ubiquitous in this industry.'] },
    { word: 'Ambiguous', level: 'advanced', phonetic: '/æmˈbɪɡ.ju.əs/', translation: '含糊不清的', examples: ['His reply was somewhat ambiguous.', 'Legal documents should not be ambiguous.'] },
    { word: 'Cognitive', level: 'advanced', phonetic: '/ˈkɑːɡ.nə.t̬ɪv/', translation: '認知的', examples: ['Cognitive development starts early in life.', 'Solving puzzles can improve cognitive skills.'] },
    { word: 'Eloquent', level: 'advanced', phonetic: '/ˈel.ə.kwənt/', translation: '雄辯的；口才流利的', examples: ['She gave an eloquent speech.', 'The book provides an eloquent defense of his views.'] },
    { word: 'Formidable', level: 'advanced', phonetic: '/fɔːrˈmɪd.ə.bəl/', translation: '令人敬畏的；難對付的', examples: ['The opponent was a formidable player.', 'She faced a formidable task ahead.'] },
    { word: 'Impeccable', level: 'advanced', phonetic: '/ɪmˈpek.ə.bəl/', translation: '無懈可擊的', examples: ['Her English is impeccable.', 'His behavior during the event was impeccable.'] },
    { word: 'Lucid', level: 'advanced', phonetic: '/ˈluː.sɪd/', translation: '清晰明瞭的', examples: ['The article provides a lucid explanation.', 'He gave a lucid account of the events.'] },
    { word: 'Paramount', level: 'advanced', phonetic: '/ˈper.ə.maʊnt/', translation: '至上的；首要的', examples: ['Safety is paramount in this mission.', 'The needs of the patient are paramount.'] },
    { word: 'Synthesis', level: 'advanced', phonetic: '/ˈsɪn.θə.sɪs/', translation: '綜合；合成', examples: ['The essay is a synthesis of several ideas.', 'Proteins are produced through chemical synthesis.'] },
    { word: 'Tangible', level: 'advanced', phonetic: '/ˈtæn.dʒə.bəl/', translation: '實體的；有形的', examples: ['We need tangible evidence of success.', 'The results are finally tangible and clear.'] },
    { word: 'Benevolent', level: 'advanced', phonetic: '/bəˈnev.əl.ənt/', translation: '仁慈的', examples: ['He was a benevolent ruler.', 'The benevolent society helps children in need.'] },
    { word: 'Collaborative', level: 'advanced', phonetic: '/kəˈlæb.ɚ.ə.tɪv/', translation: '協作的', examples: ['They take a collaborative approach to design.', 'Success depends on a collaborative effort.'] },
    { word: 'Dichotomy', level: 'advanced', phonetic: '/daɪˈkɑː.t̬ə.mi/', translation: '二分法', examples: ['There is a clear dichotomy between the two approaches.', 'The book explores the dichotomy between nature and nurture.'] },
    { word: 'Ephemeral', level: 'advanced', phonetic: '/ɪˈfem.ɚ.əl/', translation: '短暫的', examples: ['Fame in the age of the internet is ephemeral.', 'The beauty of the sunset is ephemeral.'] },
    { word: 'Fruition', level: 'advanced', phonetic: '/fruːˈɪʃ.ən/', translation: '實現；結果', examples: ['Their plans finally came to fruition.', 'After years of work, the project came to fruition.'] },
    { word: 'Gregarious', level: 'advanced', phonetic: '/ɡrɪˈɡer.i.əs/', translation: '愛社交的', examples: ['She is a gregarious and outgoing person.', 'He is very gregarious and has many friends.'] },
    { word: 'Inherent', level: 'advanced', phonetic: '/ɪnˈhɪr.ənt/', translation: '固有的', examples: ['The risk is inherent in any investment.', 'Power is inherent in his position.'] },
    { word: 'Juxtapose', level: 'advanced', phonetic: '/ˌdʒʌk.stəˈpoʊz/', translation: '並置', examples: ['He juxtaposed two different cultures in his book.', 'The artist juxtaposed bright colors with dark ones.'] },
    { word: 'Lethargic', level: 'advanced', phonetic: '/ləˈθɑːr.dʒɪk/', translation: '無精打采的', examples: ['I was feeling lethargic after a big meal.', 'The hot weather made everyone lethargic.'] },
    { word: 'Meticulous', level: 'advanced', phonetic: '/məˈtɪk.jə.ləs/', translation: '一絲不苟的', examples: ['He is meticulous in his work.', 'She gave a meticulous account of the events.'] },
    { word: 'Nostalgia', level: 'advanced', phonetic: '/nɑːˈstæl.dʒə/', translation: '懷舊', examples: ['The old songs filled him with nostalgia.', 'I have a sense of nostalgia for the house where I grew up.'] },
    { word: 'Ominous', level: 'advanced', phonetic: '/ˈɑː.mə.nəs/', translation: '不祥的', examples: ['There were ominous dark clouds in the sky.', 'The situation took an ominous turn.'] },
    { word: 'Pragmatic', level: 'advanced', phonetic: '/præɡˈmæt̬.ɪk/', translation: '務實的', examples: ['In business, you have to be pragmatic.', 'She takes a pragmatic approach to life.'] },
    { word: 'Quandary', level: 'advanced', phonetic: '/ˈkwɑːn.dri/', translation: '窘境', examples: ['I was in a quandary about what to do.', 'The company was in a financial quandary.'] },
    { word: 'Rhetoric', level: 'advanced', phonetic: '/ˈret̬.ɚ.ɪk/', translation: '修辭；花言巧語', examples: ['His speech was full of empty rhetoric.', 'The politician used powerful rhetoric.'] },
    { word: 'Subtle', level: 'advanced', phonetic: '/ˈsʌt̬.əl/', translation: '微妙的', examples: ['There are subtle differences between the two.', 'She gave me a subtle hint.'] },
    { word: 'Tenacious', level: 'advanced', phonetic: '/təˈneɪ.ʃəs/', translation: '頑強的', examples: ['He is a tenacious negotiator.', 'She has a tenacious personality.'] },
    { word: 'Unprecedented', level: 'advanced', phonetic: '/ʌnˈpres.ə.den.t̬ɪd/', translation: '史無前例的', examples: ['The situation is unprecedented.', 'This discovery is unprecedented in history.'] },
    { word: 'Vindication', level: 'advanced', phonetic: '/ˌvɪn.dəˈkeɪ.ʃən/', translation: '辯護；平反', examples: ['The discovery was a vindication of his theories.', 'She felt a sense of vindication.'] },
    { word: 'Whimsical', level: 'advanced', phonetic: '/ˈwɪm.zɪ.kəl/', translation: '異想天開的', examples: ['She has a whimsical sense of humor.', 'The story is very whimsical.'] },
    { word: 'Xenophobia', level: 'advanced', phonetic: '/ˌzen.əˈfoʊ.bi.ə/', translation: '仇外心理', examples: ['The increase in xenophobia is worrying.', 'Governments must fight against xenophobia.'] },
    { word: 'Zealous', level: 'advanced', phonetic: '/ˈzel.əs/', translation: '熱心的', examples: ['They are zealous supporters of the environmental movement.', 'He is a zealous worker.'] },
    { word: 'Aberration', level: 'advanced', phonetic: '/ˌæb.əˈreɪ.ʃən/', translation: '異常情況', examples: ['The incident was a temporary aberration.', 'His behavior was a complete aberration.'] },
    { word: 'Belie', level: 'advanced', phonetic: '/bɪˈlaɪ/', translation: '掩飾', examples: ['Her smile belied her true feelings.', 'The results belie the claims.'] },
    { word: 'Castigate', level: 'advanced', phonetic: '/ˈkæs.tə.ɡeɪt/', translation: '嚴厲斥責', examples: ['The teacher castigated the students for their behavior.', 'He was castigated for his failure.'] }
];

const PHRASES_DB = [
    // --- Beginner (A1-A2) ---
    { phrase: "How's it going?", level: "beginner", translation: "最近怎麼樣？", meaning: "A casual way to ask how someone is.", examples: ["Hey Alex, how's it going?", "I haven't seen you in a while, how's it going?"] },
    { phrase: "Nice to meet you.", level: "beginner", translation: "很高興認識你", meaning: "Used when meeting someone for the first time.", examples: ["Hi, I'm Sarah. Nice to meet you.", "Nice to meet you too!"] },
    { phrase: "Can you help me?", level: "beginner", translation: "你能幫我嗎？", meaning: "Asking for assistance.", examples: ["Excuse me, can you help me with this bag?", "Can you help me find the library?"] },
    { phrase: "I'm looking for...", level: "beginner", translation: "我在找...", meaning: "Searching for something or someone.", examples: ["I'm looking for the train station.", "I'm looking for my keys."] },
    { phrase: "How much is this?", level: "beginner", translation: "這個多少錢？", meaning: "Asking for the price.", examples: ["How much is this shirt?", "Excuse me, how much is this?"] },
    { phrase: "Catch you later.", level: "beginner", translation: "待會見", meaning: "Informal way to say goodbye.", examples: ["I have to go now. Catch you later!", "Great talking to you. Catch you later."] },
    { phrase: "Have a good one.", level: "beginner", translation: "祝你有個愉快的一天", meaning: "A polite way to say goodbye.", examples: ["Thanks for the help. Have a good one!", "See you tomorrow. Have a good one."] },
    { phrase: "No problem.", level: "beginner", translation: "沒問題 / 不客氣", meaning: "Used in response to 'Thank you' or an apology.", examples: ["Thanks for the help! - No problem.", "Sorry I'm late. - No problem at all."] },
    { phrase: "Excuse me.", level: "beginner", translation: "不好意思 / 請問", meaning: "Used to get someone's attention or apologize politely.", examples: ["Excuse me, do you have the time?", "Excuse me, I need to get through."] },
    { phrase: "Long time no see.", level: "beginner", translation: "好久不見", meaning: "Said when you haven't seen someone for a long time.", examples: ["Hey Mark! Long time no see.", "Wow, long time no see! How have you been?"] },
    { phrase: "What do you do?", level: "beginner", translation: "你是做什麼工作的？", meaning: "Asking about someone's occupation.", examples: ["So, what do you do for a living?", "What do you do? I'm a teacher."] },
    { phrase: "I don't think so.", level: "beginner", translation: "我不這麼認為", meaning: "Disagreeing politely.", examples: ["Is it going to rain? - I don't think so.", "Do you like this color? - I don't think so."] },
    { phrase: "That's a good idea.", level: "beginner", translation: "那是個好主意", meaning: "Agreeing with a suggestion.", examples: ["Let's go to the park. - That's a good idea.", "We should call him. - That's a good idea."] },
    { phrase: "Take care.", level: "beginner", translation: "保重", meaning: "A friendly way to say goodbye.", examples: ["I'll see you next week. Take care!", "Have a safe flight and take care."] },
    { phrase: "See you soon.", level: "beginner", translation: "很快見", meaning: "Saying goodbye to someone you will see again shortly.", examples: ["I'm leaving now. See you soon!", "See you soon at the party."] },

    // --- Intermediate (B1-B2) ---
    { phrase: "Keep in touch.", level: "intermediate", translation: "保持聯絡", meaning: "To remain in contact with someone.", examples: ["Let's keep in touch after you move.", "We should definitely keep in touch."] },
    { phrase: "To be honest.", level: "intermediate", translation: "老實說", meaning: "Used to introduce a truthful opinion.", examples: ["To be honest, I didn't like the movie.", "To be honest, I'm a bit tired."] },
    { phrase: "In terms of...", level: "intermediate", translation: "就...而言", meaning: "Regarding a specific aspect.", examples: ["In terms of price, this one is better.", "How does it look in terms of quality?"] },
    { phrase: "As far as I'm concerned.", level: "intermediate", translation: "就我而言", meaning: "In my opinion or from my perspective.", examples: ["As far as I'm concerned, we are finished.", "As far as I'm concerned, the case is closed."] },
    { phrase: "Make a decision.", level: "intermediate", translation: "做決定", meaning: "To choose something after thinking.", examples: ["I need some time to make a decision.", "Have you made a decision yet?"] },
    { phrase: "Take it easy.", level: "intermediate", translation: "放輕鬆 / 別太拼命", meaning: "To relax or not work too hard.", examples: ["You look stressed. Take it easy!", "I'm going to take it easy this weekend."] },
    { phrase: "Get used to...", level: "intermediate", translation: "習慣於...", meaning: "To become accustomed to something.", examples: ["I'm getting used to the cold weather.", "It takes time to get used to a new job."] },
    { phrase: "Looking forward to...", level: "intermediate", translation: "期待...", meaning: "Waiting for something with excitement.", examples: ["I'm looking forward to our trip.", "We are looking forward to seeing you."] },
    { phrase: "By the way.", level: "intermediate", translation: "順帶一提", meaning: "Used to introduce a new topic in conversation.", examples: ["By the way, have you seen the news?", "I'm going to the store. By the way, do you need anything?"] },
    { phrase: "In other words.", level: "intermediate", translation: "換句話說", meaning: "Explaining something in a different way.", examples: ["He is very busy. In other words, he can't come.", "In other words, we need to start over."] },
    { phrase: "Figure out", level: "intermediate", translation: "想出 / 弄明白", meaning: "To understand or solve a problem.", examples: ["I can't figure out how this works.", "We need to figure out a way to win."] },
    { phrase: "Fill in", level: "intermediate", translation: "填寫", meaning: "To complete a form or document.", examples: ["Please fill in your name and address.", "Can you fill in this application?"] },
    { phrase: "Give up", level: "intermediate", translation: "放棄", meaning: "To stop trying or doing something.", examples: ["Don't give up on your dreams.", "He decided to give up smoking."] },
    { phrase: "Go on", level: "intermediate", translation: "繼續", meaning: "To continue doing something.", examples: ["Please go on with your story.", "Life must go on."] },
    { phrase: "Hang out", level: "intermediate", translation: "閒逛 / 鬼混", meaning: "To spend time relaxing with others.", examples: ["Do you want to hang out this weekend?", "We used to hang out at the mall."] },

    // --- Advanced (C1-C2) ---
    { phrase: "Off the top of my head.", level: "advanced", translation: "不假思索地 / 憑當下記憶", meaning: "From memory, without giving it much thought.", examples: ["Off the top of my head, I think it costs $50.", "I can't tell you the exact number off the top of my head."] },
    { phrase: "Cut to the chase.", level: "advanced", translation: "開門見山 / 切入正題", meaning: "To get to the main point without wasting time.", examples: ["Stop talking about the weather and cut to the chase.", "Let's cut to the chase: how much will it cost?"] },
    { phrase: "Under the weather.", level: "advanced", translation: "身體不適", meaning: "Feeling slightly ill or sick.", examples: ["I'm feeling a bit under the weather today.", "He stayed home because he was under the weather."] },
    { phrase: "Once in a blue moon.", level: "advanced", translation: "千載難逢 / 極其罕見", meaning: "Very rarely.", examples: ["My brother visits me once in a blue moon.", "We go out to dinner once in a blue moon."] },
    { phrase: "Piece of cake.", level: "advanced", translation: "易如反掌", meaning: "Something that is very easy to do.", examples: ["The exam was a piece of cake.", "Don't worry, it's a piece of cake."] },
    { phrase: "A blessing in disguise.", level: "advanced", translation: "塞翁失馬，焉知非福", meaning: "Something that seems bad but leads to a good result.", examples: ["Losing my job was a blessing in disguise.", "The delay turned out to be a blessing in disguise."] },
    { phrase: "Beat around the bush.", level: "advanced", translation: "拐彎抹角", meaning: "Avoiding the main topic or not being direct.", examples: ["Stop beating around the bush and answer the question.", "He always beats around the bush when he's nervous."] },
    { phrase: "Call it a day.", level: "advanced", translation: "今天就到此為止 / 收工", meaning: "To stop working for the rest of the day.", examples: ["It's late, let's call it a day.", "We've done enough for now. Let's call it a day."] },
    { phrase: "The best of both worlds.", level: "advanced", translation: "兩全其美", meaning: "A situation where you can enjoy the advantages of two different things.", examples: ["She has the best of both worlds: a great job and a happy family.", "Living in the city but working from home gives you the best of both worlds."] },
    { phrase: "Bite the bullet.", level: "advanced", translation: "咬緊牙關 / 硬著頭皮", meaning: "To accept something difficult or unpleasant.", examples: ["I hate going to the dentist, but I'll just have to bite the bullet.", "It's time to bite the bullet and tell him the truth."] },
    { phrase: "Back to the drawing board", level: "advanced", translation: "推倒重來", meaning: "Starting over because a previous attempt failed.", examples: ["The project was rejected, so it's back to the drawing board.", "We need to go back to the drawing board on this design."] },
    { phrase: "Barking up the wrong tree", level: "advanced", translation: "搞錯對象 / 抓錯重點", meaning: "Following the wrong course of action or line of thought.", examples: ["If you think I'm the one who did it, you're barking up the wrong tree.", "The police are barking up the wrong tree in this investigation."] },
    { phrase: "Break the ice", level: "advanced", translation: "打破僵局", meaning: "To do or say something that makes people feel more relaxed.", examples: ["A joke can help to break the ice.", "He was the first to speak and break the ice."] },
    { phrase: "Burn the midnight oil", level: "advanced", translation: "通宵達旦", meaning: "To work late into the night.", examples: ["I have a big exam tomorrow, so I'll be burning the midnight oil.", "The team has been burning the midnight oil to finish the project."] },
    { phrase: "Hit the nail on the head", level: "advanced", translation: "一針見血", meaning: "To describe exactly what is causing a situation or problem.", examples: ["You hit the nail on the head when you said we need more time.", "His analysis hit the nail on the head."] }
];
